name: crunk_net
version: 3.1.0
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    angular: any
    browser: '>=0.10.0 <0.11.0'
    route_hierarchical: '>=0.5.0 <0.7.0'
    script_inliner: '>=1.0.0 <2.0.0'
    web_components: any
    range: any
transformers:
- angular:
    html_files:
      - view/home.html
      - view/choose.html
      - lib/controller/choices.html
      - lib/controller/home.html
- script_inliner